name: example
description: Example project for v_flutter_core

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  v_flutter_core:
    path: "../"
  reactive_forms: ^17.0.1
  mask_text_input_formatter: ^2.7.0
  collection: ^1.17.2
  entry: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
