name: v_flutter_core
description: vlabs core library
version: 0.0.1

environment:
  sdk: ^3.1.0
  flutter: ^3.13.0

dependencies:
  collection: ^1.17.1
  easy_debounce: ^2.0.3
  entry: ^0.0.9
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_portal: ^1.1.4
  gap: ^3.0.1
  hooks_riverpod: ^2.4.0
  reactive_forms: ^16.1.0
  reactive_forms_annotations: ^4.0.0
  riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  theme_tailor_annotation: ^2.0.0
  universal_html: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.6
  lint: ^2.2.0
  reactive_forms_generator: ^4.0.0
  riverpod_generator: ^2.3.2
  theme_tailor: ^2.0.0
