name: v_flutter_core
description: vlabs core library
repository: https://github.com/Vlabs-development/v_flutter_core
version: 0.0.4

environment:
  sdk: ^3.1.0
  flutter: '>=3.19.3'

dependencies:
  collection: ^1.17.1
  easy_debounce: ^2.0.3
  entry: ^0.0.9
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_portal: ^1.1.4
  gap: ^3.0.1
  hooks_riverpod: ^2.4.0
  # Ensure to keep  `/src/widgets/reactive_text_field/reactive_text_field.dart` in sync
  reactive_forms: ^16.1.1
  reactive_forms_annotations: ^4.0.0
  riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  rxdart: ^0.27.7
  theme_tailor_annotation: ^2.0.0
  time: ^2.1.4
  universal_html: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.6
  lint: ^2.2.0
  mocktail: ^1.0.3
  reactive_forms_generator: ^4.0.0
  riverpod_generator: ^2.3.2
  test: ^1.25.2
  theme_tailor: ^2.0.0
