name: v_flutter_core
description: A core library for Flutter applications, offering essential tools and utilities for streamlined development and state management.
repository: https://github.com/Vlabs-development/v_flutter_core
version: 0.0.13

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  collection: ^1.17.1
  easy_debounce: ^2.0.3
  entry: ^1.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_portal: ^1.1.4
  fpdart: ^1.1.0
  gap: ^3.0.1
  hooks_riverpod: ^2.4.0
  # Ensure to keep  `/src/widgets/reactive_text_field/reactive_text_field.dart` in sync
  reactive_forms: ^17.0.1
  reactive_forms_annotations: ^5.0.0
  riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  rxdart: ^0.27.3
  theme_tailor_annotation: ^3.0.1
  time: ^2.1.4
  universal_html: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.6
  lint: ^2.2.0
  mocktail: ^1.0.3
  reactive_forms_generator: ^5.0.5
  riverpod_generator: ^2.3.2
  test: ^1.25.2
  theme_tailor: ^3.0.1
